GET http://localhost:5005/

###

GET http://localhost:5005/Order/

###
GET http://localhost:5005/Order/2

###
POST http://localhost:5005/Order/
Content-Type: application/json

{
    "GameId": 5,
    "CustomerId": 1
}
###
PUT http://localhost:5005/Order/5
Content-Type: application/json

{
    "GameId": 1,
    "CustomerId": 2
}

###
DELETE http://localhost:5005/Order/2