GET http://localhost:5005/

###

GET http://localhost:5005/Order/

###
GET http://localhost:5005/Order/1

###
POST http://localhost:5005/Order/
Content-Type: application/json

{
    "GameIds": [4, 3],
    "CustomerId": 2
}
###
PUT http://localhost:5005/Order/1
Content-Type: application/json

{
    "GameIds": [2, 1],
    "CustomerId": 1
}

###
DELETE http://localhost:5005/Order/2